/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pokemon;

import chatmessage.Message;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.ObjectOutputStream;
import java.io.PrintWriter;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author lenovo
 */
public class PokemonGUI extends javax.swing.JFrame {

    private Socket socket;
    private ObjectOutputStream out;
    int statenewuser=0;
    BufferedReader in;
    String username = null;
    String newuser = null;
    Thread t,b;
    ThreadRead tr;
    Game game;
    boolean connex=false;
    //String apa;
    pokemon p;
    String Nama; 
    int Health;
    int buff;
    int exp;
    int Attack1;
    int Attack2;
    int Attack3;
    String Skill1;
    String Skill2;
    String Skill3;
    String Skill4;
    String Ket1;
    String Ket2;
    String Ket3;
    String Ket4;
    
    int healthMusuh;
    int namaMusuh;
    
    public void ListenThread() 
    {
        try {
            tr = new ThreadRead(socket,chatTextArea, username, jLabel2, jLabel5, jLabel8);
            t = new Thread(tr);
            t.start();
            walking_Ball();
        } catch (IOException ex) {
            Logger.getLogger(PokemonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void walking_Ball() throws IOException {
         //set game
        //game = new Game(gamePanel);
        game = new Game(socket, tr, username, this);
        b = new Thread((Runnable) game);
        b.start();
        
    }
    
    public class IncomingMsg implements Runnable
    {
        @Override
        public void run() 
        {
            String data;

            try 
            {
                while(true){
                    System.out.println("Test1");
                    data = in.readLine();
                    chatTextArea.setText(chatTextArea.getText().trim()+"\n"+data);  
            }
           }catch(Exception ex) { }
        }
    }
    /**
     * Creates new form PokemonGUI
     */
    public PokemonGUI() {
        initComponents();
        chatTextArea.setEditable(false);
        jTextArea2.setEditable(false);
        jTextArea3.setEditable(false);
        jTextArea4.setEditable(false);
        jTextArea5.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        playerTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chatTextArea = new javax.swing.JTextArea();
        connect_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        readyBUtton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Health");

        jLabel8.setText("Pokemon C");

        jButton3.setLabel("Attack C");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setLabel("Attack D");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        playerTextField.setText("Pikachu");
        playerTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playerTextFieldActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        chatTextArea.setColumns(20);
        chatTextArea.setRows(5);
        chatTextArea.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                chatTextAreaInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jScrollPane1.setViewportView(chatTextArea);

        connect_button.setText("Connect");
        connect_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connect_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Pokemon A");

        jLabel2.setText("Health");

        jButton1.setLabel("Attack A");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setLabel("AttackB");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Enemy");

        readyBUtton.setText("Ready");
        readyBUtton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyBUttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(playerTextField, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(readyBUtton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(connect_button)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(connect_button)
                    .addComponent(readyBUtton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton1)
                                    .addComponent(jButton4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(playerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendButton))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Battle", jPanel1);

        jLabel11.setText("Pokemon A");

        jLabel12.setText("Health");

        jLabel13.setText("Skill A");

        jScrollPane2.setToolTipText("");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel14.setText("Skill B");

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jLabel15.setText("Skill C");

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jLabel16.setText("Skill D");

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jLabel17.setText("jLabel17");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(73, 73, 73)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel17))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Info", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void readyBUttonActionPerformed(java.awt.event.ActionEvent evt) {                                            
        if(game.x == game.x1 && game.y == game.x2){
            jLabel5.setText(tr.enemyHP);
            jLabel8.setText(tr.newuser);
        }
        else{
            System.out.println("kordinat belum sama");
        }
    }                                           

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(tr.flag==0){
        String attack = String.valueOf(Attack2);
        String Serangan = "Serang: "+ attack + " " + Skill2;
        String namaSerangan = Skill2;
        Message objMsg = new Message();
        objMsg.setMessage(Serangan);
        objMsg.setSender(username);
        String temp1=jLabel5.getText();
        int temp2=Integer.parseInt(temp1);
        temp2=temp2-Attack2;
        temp1=String.valueOf(temp2);
        jLabel5.setText(temp1);
        try {
            tr.send(objMsg);
        } catch (IOException ex) {
            Logger.getLogger(PokemonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tr.flag=1;
        }
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.out.println(tr.flag);
        if(tr.flag == 0){
        String attack = String.valueOf(Attack1);
        String Serangan = "Serang: "+ attack + " " + Skill1;
        String namaSerangan = Skill1;
        Message objMsg = new Message();
        objMsg.setMessage(Serangan);
        objMsg.setSender(username);
        String temp1=jLabel5.getText();
        int temp2=Integer.parseInt(temp1);
        temp2=temp2-Attack1;
        temp1=String.valueOf(temp2);
        jLabel5.setText(temp1);
        try {
            tr.send(objMsg);
        } catch (IOException ex) {
            Logger.getLogger(PokemonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tr.flag = 1;
        }
        System.out.println(tr.flag);
    }                                        

    private void connect_buttonActionPerformed(java.awt.event.ActionEvent evt) {                                               
        connex = true;
        try {
            socket = new Socket("localhost", 6666);
            ListenThread();
            in = new BufferedReader(new InputStreamReader(System.in));
            //this.out = new ObjectOutputStream(this.socket.getOutputStream());
            //String username = in.readLine();
            /*
            while(true) {
                String msg = in.readLine();
                if(msg.equalsIgnoreCase("end")) {
                    break;
                }

                Message objMsg = new Message();
                objMsg.setMessage(msg);
                objMsg.setSender(username);
                tr.send(objMsg);
            }
            */
            //tr.stop();
        } catch (IOException ex) {
            Logger.getLogger(PokemonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                              

    private void chatTextAreaInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        if(connex==false)
        {
            String apa =playerTextField.getText();
            p = new pokemon(apa);
            Nama=p.Nama;
            Health=p.Health;
            Attack1=p.Attack1;
            Attack2=p.Attack2;
            Attack3=p.Attack3;
            Skill1=p.Skill1;
            Skill2=p.Skill2;
            Skill3=p.Skill3;
            Skill4=p.Skill4;
            Ket1=p.Ket1;
            Ket2=p.Ket2;
            Ket3=p.Ket3;
            Ket4=p.Ket4;
            buff=p.buff;
            exp=p.exp;

            jLabel1.setText(Nama);
            jLabel2.setText(String.valueOf(Health));
            jButton1.setText(Skill1);
            jButton2.setText(Skill2);
            jButton3.setText(Skill3);
            jButton4.setText(Skill4);
            jLabel11.setText(Nama);
            jLabel17.setText(String.valueOf(Health));
            jLabel13.setText(Skill1);
            jLabel14.setText(Skill2);
            jLabel15.setText(Skill3);
            jLabel16.setText(Skill4);
            jTextArea2.append(Ket1);
            jTextArea3.append(Ket2);
            jTextArea4.append(Ket3);
            jTextArea5.append(Ket4);

        }
        if(connex = true){
            if(username == null){
                System.out.println("user_test");
                username = playerTextField.getText();
            }
            else{
                try {
                    String msg = playerTextField.getText();
                    Message objMsg = new Message();
                    objMsg.setMessage(msg);
                    objMsg.setSender(username);
                    tr.send(objMsg);
                } catch (IOException ex) {
                    Logger.getLogger(PokemonGUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }                                          

    private void playerTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(tr.flag == 0){
        String darah = null;
        String attack = String.valueOf(buff);
        String namaSerangan = Skill4;
        if(Nama.equals("Squirtle")||Nama.equals("Charmander"))
        {
            int temp1=(Attack1 * 15)/100;
            int temp2=(Attack2 * 15)/100;
            int temp3=(Attack3 * 15)/100;
            Attack1=Attack1 + temp1;
            Attack2=Attack2 + temp2;
            Attack3=Attack3 + temp3;
            String temp5=jLabel2.getText();
            darah = temp5;
        }
        else{
            String temp1=jLabel2.getText();
            int temp2=Integer.parseInt(temp1);
            int temp3=(temp2*15)/100;
            temp2=temp2+temp3;
            temp1=String.valueOf(temp2);
            darah = temp1;
            jLabel2.setText(temp1);
        }
        String Serangan ="Serang: "+Skill4+" "+"buff: "+attack+" % "+ darah;
        Message objMsg = new Message();
        objMsg.setMessage(Serangan);
        objMsg.setSender(username);
        try {
            tr.send(objMsg);
        } catch (IOException ex) {
            Logger.getLogger(PokemonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tr.flag = 1;
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(tr.flag == 0){
        String attack = String.valueOf(Attack3);
        String Serangan = "Serang: "+ attack + " " + Skill3;
        String namaSerangan = Skill3;
        Message objMsg = new Message();
        objMsg.setMessage(Serangan);
        objMsg.setSender(username);
        String temp1=jLabel5.getText();
        int temp2=Integer.parseInt(temp1);
        temp2=temp2-Attack3;
        temp1=String.valueOf(temp2);
        jLabel5.setText(temp1);
        try {
            tr.send(objMsg);
        } catch (IOException ex) {
            Logger.getLogger(PokemonGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        tr.flag = 1;
        }
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokemonGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokemonGUI().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTextArea chatTextArea;
    private javax.swing.JButton connect_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField playerTextField;
    private javax.swing.JButton readyBUtton;
    private javax.swing.JButton sendButton;
    // End of variables declaration                   
    public void send(Message message) throws IOException {
        this.out.writeObject(message);
        this.out.flush();
        this.out.reset();
    }
}
